title: 我要中大John
description: I want big John
url: "https://cyc6221.github.io"
baseurl: "/I-want-big-John"
theme: minima

# Author info
author: CY
email: s24343162@gmail.com
github_username: cyc6221

# Build settings
markdown: kramdown
highlighter: rouge

header_pages:
  # - index.md
  - pages/638.md # 威力彩
  - pages/649.md # 大樂透
  - pages/539.md # 今彩539
  - pages/instant.md # 刮刮樂
  - pages/list.md # 紀錄

plugins:
  - jekyll-git-metadata
  - jekyll-sitemap

collections:
  articles:
    output: true
    permalink: /articles/:path/
  list:
    output: true
    permalink: /list/:path/

defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: page
      toc: false

  - scope:
      path: ""
      type: list
    values:
      layout: page
      toc: false