title: 我要中大獎
description: wo-yao-chung-ta-chiang
url: "https://cyc6221.github.io"
baseurl: "/wo-yao-chung-ta-chiang"
theme: minima

# Author info
author: CY
email: s24343162@gmail.com
github_username: cyc6221

# Build settings
markdown: kramdown
highlighter: rouge

header_pages:
  # - index.md
  - pages/638.md # 威力彩
  - pages/649.md # 大樂透
  - pages/539.md # 今彩539

plugins:
  - jekyll-git-metadata
  - jekyll-sitemap
